import nodemailer from 'nodemailer';
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  const formData = await request.json();

  try {
    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: {
        user: 'dminphotography@gmail.com', // Your email address
        pass: 'mfyr lrwm mkxw rkto', // Gmail App Password
      },
      tls: {
        rejectUnauthorized: false, // Allow self-signed certificates
      },
    });

    const mailOptions = {
      from: '"FatimaPhotography Admin" <dminphotography@gmail.com>',
      to: 'pandasmp91@gmail.com', // Replace with your email
      subject: `New Booking Submission from ${formData.name}`,
      text: `
        You have received a new booking:

        Name: ${formData.name}
        Email: ${formData.email}
        Phone: ${formData.phone}
        Date: ${formData.date}
        Referral: ${formData.referral}
        Special Requests: ${formData.specialRequests}
        Event Type: ${formData.eventType}
        Custom Event: ${formData.customEvent}

        This message was automatically generated by FatimaPhotography.
      `,
      html: `
        <h2>New Booking Submission</h2>
        <p><strong>Name:</strong> ${formData.name}</p>
        <p><strong>Email:</strong> ${formData.email}</p>
        <p><strong>Phone:</strong> ${formData.phone}</p>
        <p><strong>Date:</strong> ${formData.date}</p>
        <p><strong>Referral:</strong> ${formData.referral}</p>
        <p><strong>Special Requests:</strong> ${formData.specialRequests}</p>
        <p><strong>Event Type:</strong> ${formData.eventType}</p>
        <p><strong>Custom Event:</strong> ${formData.customEvent}</p>
        <p>This message was automatically generated by FatimaPhotography.</p>
      `,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: 'Email sent successfully!' }, { status: 200 });
  } catch (error: any) {
    console.error('Error sending email:', error.message);
    return NextResponse.json({ error: 'Failed to send email.' }, { status: 500 });
  }
}
